version: '3.9'

services:
  reverseproxy:
    container_name: reverseproxy
    build: .
    image: reverseproxy
    ports:
      - 80:80
      - 443:443
    networks:
      - fgtanetwork

networks:
  fgtanetwork:
    name: fgtanetwork
    external: true